-- Sample seed data for Oracle schema USER_MGMT

-- Recreate triggers to ensure valid state
CREATE OR REPLACE TRIGGER TRG_COMPANY_PROFILES_BI
BEFORE INSERT ON COMPANY_PROFILES
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_COMPANY_PROFILES.NEXTVAL;
  IF :NEW.CREATED_DATE IS NULL THEN
    :NEW.CREATED_DATE := SYSDATE;
  END IF;
  IF :NEW.LAST_UPDATED_DATE IS NULL THEN
    :NEW.LAST_UPDATED_DATE := SYSDATE;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DEPARTMENTS_BI
BEFORE INSERT ON DEPARTMENTS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_DEPARTMENTS.NEXTVAL;
  IF :NEW.CREATED_DATE IS NULL THEN
    :NEW.CREATED_DATE := SYSDATE;
  END IF;
  IF :NEW.LAST_UPDATED_DATE IS NULL THEN
    :NEW.LAST_UPDATED_DATE := SYSDATE;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOOKUP_VALUES_BI
BEFORE INSERT ON LOOKUP_VALUES
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_LOOKUP_VALUES.NEXTVAL;
  IF :NEW.CREATED_DATE IS NULL THEN
    :NEW.CREATED_DATE := SYSDATE;
  END IF;
  IF :NEW.LAST_UPDATED_DATE IS NULL THEN
    :NEW.LAST_UPDATED_DATE := SYSDATE;
  END IF;
END;
/

-- Lookup values (insert only if not exists to avoid unique constraint UQ_LOOKUP_GROUP_CD)
INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Male', 1, 'GENDER', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='GENDER' AND LOOKUP_CD=1);
INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Female', 2, 'GENDER', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='GENDER' AND LOOKUP_CD=2);
INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Other', 3, 'GENDER', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='GENDER' AND LOOKUP_CD=3);

INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Admin', 1, 'POSITION', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='POSITION' AND LOOKUP_CD=1);
INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Manager', 2, 'POSITION', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='POSITION' AND LOOKUP_CD=2);
INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Staff', 3, 'POSITION', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='POSITION' AND LOOKUP_CD=3);

INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'CCCD', 1, 'ID_TYPE', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='ID_TYPE' AND LOOKUP_CD=1);
INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Passport', 2, 'ID_TYPE', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='ID_TYPE' AND LOOKUP_CD=2);

INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Active', 1, 'USER_STATUS', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='USER_STATUS' AND LOOKUP_CD=1);
INSERT INTO LOOKUP_VALUES (ID, LOOKUP_VALUE, LOOKUP_CD, LOOKUP_GROUP, STATUS_FLG, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_LOOKUP_VALUES.NEXTVAL, 'Inactive', 0, 'USER_STATUS', 1, NULL, 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM LOOKUP_VALUES WHERE LOOKUP_GROUP='USER_STATUS' AND LOOKUP_CD=0);

-- Company (insert if not exists)
INSERT INTO COMPANY_PROFILES (ID, COMPANY_NAME, STOCK_CODE, STOCK_EXCHANGE, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_COMPANY_PROFILES.NEXTVAL, 'Acme Corp', 'ACM', 'HNX', 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM COMPANY_PROFILES WHERE COMPANY_NAME='Acme Corp');

-- Department (insert if not exists)
INSERT INTO DEPARTMENTS (ID, DEPARTMENT_NAME, DESCRIPTION, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
SELECT SEQ_DEPARTMENTS.NEXTVAL, 'IT Department', 'Core IT team', 'system', SYSDATE, 'system', SYSDATE FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE DEPARTMENT_NAME='IT Department');

-- Sample user (take first matching dept/company to avoid ORA-01427)
INSERT INTO USERS (
  ID, USER_NAME, PASSWORD, FULL_NAME, BIRTH_DATE, GENDER_CD, ADDRESS, PHONE_NO, FAX_NO,
  EMAIL, IDENTITY, IDENTITY_TYPE_CD, IDENTITY_ISSUED_DATE, IDENTITY_ISSUED_PLACE,
  DEPARTMENT_ID, POSITION_CD, STATUS_FLG, COMPANY_PROFILE_ID, DESCRIPTION,
  CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE
) SELECT
  RAWTOHEX(SYS_GUID()),
  'admin01',
  'password123',
  'Admin User',
  TO_DATE('1990-01-01','YYYY-MM-DD'),
  1, -- Male
  '123 Main St',
  '0901234567',
  '0281234567',
  'admin01@example.com',
  '012345678901',
  1, -- CCCD
  TO_DATE('2020-01-01','YYYY-MM-DD'),
  'HCMC',
  (SELECT ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='IT Department' AND ROWNUM=1),
  1, -- Admin position
  1, -- Active
  (SELECT ID FROM COMPANY_PROFILES WHERE COMPANY_NAME='Acme Corp' AND ROWNUM=1),
  'Seed admin user',
  'system', SYSDATE, 'system', SYSDATE
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE USER_NAME='admin01');

COMMIT;
