
CREATE TABLE LOOKUP_VALUES (
  ID NUMBER(10,0) NOT NULL,
  LOOKUP_VALUE VARCHAR2(255) NOT NULL,
  LOOKUP_CD NUMBER(2,0) NOT NULL,
  LOOKUP_GROUP VARCHAR2(20) NOT NULL,
  STATUS_FLG NUMBER(1,0) DEFAULT 1 NOT NULL,
  DESCRIPTION VARCHAR2(255),
  CREATED_BY VARCHAR2(30) NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY VARCHAR2(30) NOT NULL,
  LAST_UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_LOOKUP_VALUES PRIMARY KEY (ID),
  CONSTRAINT UQ_LOOKUP_GROUP_CD UNIQUE (LOOKUP_GROUP, LOOKUP_CD),
  CONSTRAINT CK_LOOKUP_STATUS CHECK (STATUS_FLG IN (0,1))
);

CREATE SEQUENCE SEQ_LOOKUP_VALUES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_LOOKUP_VALUES_BI
BEFORE INSERT ON LOOKUP_VALUES
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_LOOKUP_VALUES.NEXTVAL;
  IF :NEW.CREATED_DATE IS NULL THEN
    :NEW.CREATED_DATE := SYSDATE;
  END IF;
  IF :NEW.LAST_UPDATED_DATE IS NULL THEN
    :NEW.LAST_UPDATED_DATE := SYSDATE;
  END IF;
END;
/


-- Company profiles

CREATE TABLE COMPANY_PROFILES (
  ID NUMBER(10,0) NOT NULL,
  COMPANY_NAME VARCHAR2(255) NOT NULL,
  STOCK_CODE VARCHAR2(10) NOT NULL,
  STOCK_EXCHANGE VARCHAR2(10) NOT NULL,
  CREATED_BY VARCHAR2(30) NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY VARCHAR2(30) NOT NULL,
  LAST_UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_COMPANY_PROFILES PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_COMPANY_PROFILES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_COMPANY_PROFILES_BI
BEFORE INSERT ON COMPANY_PROFILES
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_COMPANY_PROFILES.NEXTVAL;
  IF :NEW.CREATED_DATE IS NULL THEN
    :NEW.CREATED_DATE := SYSDATE;
  END IF;
  IF :NEW.LAST_UPDATED_DATE IS NULL THEN
    :NEW.LAST_UPDATED_DATE := SYSDATE;
  END IF;
END;


-- Departments

CREATE TABLE DEPARTMENTS (
  ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_NAME VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(255),
  CREATED_BY VARCHAR2(30) NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY VARCHAR2(30) NOT NULL,
  LAST_UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID)
);  

CREATE SEQUENCE SEQ_DEPARTMENTS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_DEPARTMENTS_BI
BEFORE INSERT ON DEPARTMENTS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_DEPARTMENTS.NEXTVAL;
  IF :NEW.CREATED_DATE IS NULL THEN
    :NEW.CREATED_DATE := SYSDATE;
  END IF;
  IF :NEW.LAST_UPDATED_DATE IS NULL THEN
    :NEW.LAST_UPDATED_DATE := SYSDATE;
  END IF;
END;
/


-- Users

CREATE TABLE USERS (
  ID VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL,
  PASSWORD VARCHAR2(255) NOT NULL,
  FULL_NAME VARCHAR2(50) NOT NULL,
  BIRTH_DATE DATE,
  GENDER_CD NUMBER(2,0),
  ADDRESS VARCHAR2(255),
  PHONE_NO VARCHAR2(20),
  FAX_NO VARCHAR2(20),
  EMAIL VARCHAR2(50) NOT NULL,
  IDENTITY VARCHAR2(20),
  IDENTITY_TYPE_CD NUMBER(2,0),
  IDENTITY_ISSUED_DATE DATE,
  IDENTITY_ISSUED_PLACE VARCHAR2(20),
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  POSITION_CD NUMBER(2,0) NOT NULL,
  STATUS_FLG NUMBER(1,0) DEFAULT 1 NOT NULL,
  COMPANY_PROFILE_ID NUMBER(10,0) NOT NULL,
  DESCRIPTION VARCHAR2(255),
  CREATED_BY VARCHAR2(30) NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY VARCHAR2(30) NOT NULL,
  LAST_UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (ID),
  CONSTRAINT UQ_USERS_USERNAME UNIQUE (USER_NAME),
  CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CK_USERS_STATUS CHECK (STATUS_FLG IN (0,1)),
  CONSTRAINT FK_USERS_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
  CONSTRAINT FK_USERS_COMPANY FOREIGN KEY (COMPANY_PROFILE_ID) REFERENCES COMPANY_PROFILES(ID)
);

CREATE INDEX IDX_USERS_DEPT ON USERS (DEPARTMENT_ID);
CREATE INDEX IDX_USERS_POSITION ON USERS (POSITION_CD);
CREATE INDEX IDX_USERS_STATUS ON USERS (STATUS_FLG);


-- User change history  

CREATE TABLE USER_HISTORY (
  ID VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  USER_ID VARCHAR2(36) NOT NULL,
  FIELD_NAME VARCHAR2(20) NOT NULL,
  OLD_VALUE VARCHAR2(255) NOT NULL,
  NEW_VALUE VARCHAR2(255) NOT NULL,
  CHANGED_BY VARCHAR2(30) NOT NULL,
  CHANGED_DATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_USER_HISTORY PRIMARY KEY (ID),
  CONSTRAINT FK_USER_HISTORY_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE INDEX IDX_USER_HISTORY_USER ON USER_HISTORY (USER_ID);
CREATE INDEX IDX_USER_HISTORY_FIELD ON USER_HISTORY (FIELD_NAME);

SELECT table_name
FROM user_tables
WHERE table_name IN ('LOOKUP_VALUES', 'COMPANY_PROFILES', 'DEPARTMENTS', 'USERS', 'USER_HISTORY');
